import "./globals.css";
import Providers from "@/app/_components/Providers";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="main-container" suppressHydrationWarning>
        <Providers>
          <main>{children}</main>
        </Providers>
        <Toaster
          position="top-center"
          gutter={12}
          containerStyle={{ margin: "8px" }}
          toastOptions={{
            success: {
              duration: 3000,
            },
            error: {
              duration: 5000,
            },
            style: {
              fontSize: "16px",
              maxWidth: "500px",
              padding: "16px 24px",
              backgroundColor: "#387478",
              color: "#e2f1e7",
            },
          }}
        />
      </body>
    </html>
  );
}
